# Generated by Django 3.1.4 on 2021-02-27 10:17

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
