# Generated by Django 3.1.4 on 2021-02-27 12:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210227_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
