# Generated by Django 3.1.4 on 2021-02-27 13:07

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_topic_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='video',
        ),
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.topic')),
            ],
        ),
    ]
