# Generated by Django 3.1.4 on 2021-02-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20210227_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='video',
        ),
        migrations.AddField(
            model_name='itembase',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.topic'),
        ),
    ]
