# Generated by Django 3.1.4 on 2021-02-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20210227_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembase',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
