# Generated by Django 3.1.4 on 2021-02-27 15:03

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_itembase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
        migrations.DeleteModel(
            name='ItemBase',
        ),
    ]
