# Generated by Django 3.1.4 on 2020-12-16 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='exams_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.examstype'),
        ),
    ]
