# Generated by Django 3.1.4 on 2020-12-16 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20201216_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.subject'),
        ),
    ]
