# Generated by Django 3.1.4 on 2020-12-24 00:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20201216_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/notes')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('exams_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.examstype')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.form')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
