# Generated by Django 3.1.4 on 2021-01-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popular',
            field=models.CharField(choices=[('Popular', 'popular'), ('Normal', 'normal')], max_length=20, null=True),
        ),
    ]
