# Generated by Django 3.1.4 on 2020-12-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20201215_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(null=True, upload_to='media/subject'),
        ),
    ]
