# Generated by Django 3.1.4 on 2020-12-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_subject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(null=True, upload_to='media/notes'),
        ),
    ]
