# Generated by Django 3.1.4 on 2020-12-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
