# Generated by Django 3.1.4 on 2020-12-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_content_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
