# Generated by Django 2.0 on 2020-12-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
