# Generated by Django 2.0 on 2020-12-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
